### PR TITLE
Dq0 800 - Estimators V1.0

### PR DESCRIPTION
**Pull request by WolfgangGross**
related to:
* pull request in dq0-makeDP (branch DQ0-800 -> https://github.com/gradientzero/dq0-makedp/pull/29)
* pull request in dq0-privacy-checker (branch DQ0-800 -> https://github.com/gradientzero/dq0-privacy-checker/pull/22)
* pull request in dq0-privacy-utils (branch DQ0-792 -> https://github.com/gradientzero/dq0-privacy-utils/pull/3)
* pull request in dq0-mod-utils (branch DQ0-800 -> https://github.com/gradientzero/dq0-mod-utils/pull/10)

For testing make sure to be on the respective branches.
For integration testing see:
* makeDP: https://github.com/gradientzero/dq0-makedp/tree/DQ0-800/tests/integration_tests
* privacy-checker: https://github.com/gradientzero/dq0-privacy-checker/tree/DQ0-800/tests/integration_tests

### CODE REVIEW

**Comment by clincolnoz** [comment]
This is the regression example not census classification. 
https://github.com/gradientzero/dq0-privacy-checker/blob/DQ0-800/tests/integration_tests/run_estimator_classification_census.sh

**Comment by WolfgangGross** [comment]
> This is the regression example not census classification.
> https://github.com/gradientzero/dq0-privacy-checker/blob/DQ0-800/tests/integration_tests/run_estimator_classification_census.sh

True. I changed it

**Comment by clincolnoz** [comment]
with this i got an error. Predict is returning 0

`2021-03-17T15:40:54Z | dq0.privacy_checker.model_checker.mc_classification | DEBUG | -- Train target model
2021-03-17T15:40:54Z | dq0.privacy_checker.model_checker.mc_classification | DEBUG | Percentage freq. of target labels in train dataset (baseline for classification performance):
2021-03-17T15:40:54Z | dq0 | DEBUG |   0.0: 76.06889
2021-03-17T15:40:54Z | dq0 | DEBUG |   1.0: 23.93111
2021-03-17T15:40:54Z | dq0 | ERROR | Traceback (most recent call last):
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2021-03-17T15:40:54Z | dq0 | ERROR | "__main__", mod_spec)
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
2021-03-17T15:40:54Z | dq0 | ERROR | exec(code, run_globals)
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0-privacy-checker/dq0/privacy_checker/__main__.py", line 162, in <module>
2021-03-17T15:40:54Z | dq0 | ERROR | run()
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0-privacy-checker/dq0/privacy_checker/__main__.py", line 153, in run
2021-03-17T15:40:54Z | dq0 | ERROR | return instance.run()
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0-privacy-checker/dq0/privacy_checker/model_check_runner.py", line 278, in run
2021-03-17T15:40:54Z | dq0 | ERROR | working_folder=working_folder
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0-privacy-checker/dq0/privacy_checker/model_checker/model_checker.py", line 94, in run
2021-03-17T15:40:54Z | dq0 | ERROR | working_folder
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0-privacy-checker/dq0/privacy_checker/model_checker/model_checker.py", line 434, in check_target_model_utility_and_privacy
2021-03-17T15:40:54Z | dq0 | ERROR | gen_gap_folder
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0-privacy-checker/dq0/privacy_checker/model_checker/mc_classification.py", line 298, in estimate_generalization_gap
2021-03-17T15:40:54Z | dq0 | ERROR | y_train_np_a, pred_y_train_np_a)
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0/dq0/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
2021-03-17T15:40:54Z | dq0 | ERROR | return f(*args, **kwargs)
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0/dq0/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 202, in accuracy_score
2021-03-17T15:40:54Z | dq0 | ERROR | y_type, y_true, y_pred = _check_targets(y_true, y_pred)
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0/dq0/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 83, in _check_targets
2021-03-17T15:40:54Z | dq0 | ERROR | check_consistent_length(y_true, y_pred)
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0/dq0/lib/python3.7/site-packages/sklearn/utils/validation.py", line 259, in check_consistent_length
2021-03-17T15:40:54Z | dq0 | ERROR | lengths = [_num_samples(X) for X in arrays if X is not None]
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0/dq0/lib/python3.7/site-packages/sklearn/utils/validation.py", line 259, in <listcomp>
2021-03-17T15:40:54Z | dq0 | ERROR | lengths = [_num_samples(X) for X in arrays if X is not None]
2021-03-17T15:40:54Z | dq0 | ERROR |   File "/Users/cl/Documents/projects/dq0/dq0/lib/python3.7/site-packages/sklearn/utils/validation.py", line 203, in _num_samples
2021-03-17T15:40:54Z | dq0 | ERROR | " a valid collection." % x)
2021-03-17T15:40:54Z | dq0 | ERROR | TypeError
2021-03-17T15:40:54Z | dq0 | ERROR | :
2021-03-17T15:40:54Z | dq0 | ERROR | Singleton array 0 cannot be considered a valid collection.
(dq0) cl@Craigs-MacBook-Pro dq0-privacy-checker % `

**Comment by clincolnoz** [comment]
https://github.com/gradientzero/dq0-privacy-checker/blob/DQ0-800/tests/integration_tests/run_estimator_classification_census.sh

gave an error https://github.com/gradientzero/dq0-privacy-checker/blob/DQ0-800/dq0/privacy_checker/model_checker/mc_classification.py#L306 is returning 0

I checked X_test_np_a is ok and it looks fine but maybe because its np.

**Comment by WolfgangGross** [comment]
I fixed this is makeDP some minutes ago, pull and try again

**Review by clincolnoz — APPROVED** [review]

**Pull request merged**
